[build]
  publish = "static"
  command = "pip install -r requirements.txt"

[functions]
  directory = "netlify/functions"

# Đây là phần quan trọng nhất. Hãy đảm bảo nó được viết chính xác.
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
  # THÊM DÒNG NÀY VÀO. Đôi khi Netlify yêu cầu nó.
  force = true 